version: "2.3"

services:
  dev:
    environment:
      ALLOWED_IMAGES: "quay.io/sharelatex/texlive-full:2017.1"
      TEXLIVE_IMAGE: quay.io/sharelatex/texlive-full:2017.1
      TEXLIVE_IMAGE_USER: "tex"
      SHARELATEX_CONFIG: /app/config/settings.defaults.coffee
      DOCKER_RUNNER: "true"
      COMPILES_HOST_DIR: $PWD/compiles
      SYNCTEX_BIN_HOST_PATH: $PWD/bin/synctex
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./compiles:/app/compiles
      - ./cache:/app/cache
      - ./bin/synctex:/app/bin/synctex

      
  ci:
    environment:
      ALLOWED_IMAGES: ${TEXLIVE_IMAGE}
      TEXLIVE_IMAGE: quay.io/sharelatex/texlive-full:2017.1
      TEXLIVE_IMAGE_USER: "tex"
      SHARELATEX_CONFIG: /app/config/settings.defaults.coffee
      DOCKER_RUNNER: "true"
      COMPILES_HOST_DIR: $PWD/compiles
      SYNCTEX_BIN_HOST_PATH: $PWD/bin/synctex
      SQLITE_PATH: /app/compiles/db.sqlite
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./compiles:/app/compiles
      - ./cache:/app/cache
      - ./bin/synctex:/app/bin/synctex
