language: node_js

node_js:
    - "0.10"

before_install:
    - npm install -g grunt-cli

install:
    - npm install
    - grunt install

before_script:
    - grunt forever:app:start

script:
    - grunt test:unit
    - grunt test:acceptance

services:
    - mongodb
