version: "2"

volumes:
  data:

services:

  test_unit:
    build: .
    image: ci/$PROJECT_NAME:$BRANCH_NAME-$BUILD_NUMBER
    user: node
    command: npm run test:unit:app

  test_acceptance:
    build: .
    image: ci/$PROJECT_NAME:$BRANCH_NAME-$BUILD_NUMBER
    working_dir: /app
    environment:
      BCRYPT_ROUNDS: 1
      REDIS_HOST: redis
      MONGO_URL: "mongodb://mongo/sharelatex"
      SHARELATEX_ALLOW_PUBLIC_ACCESS: 'true'
      PROJECT_HISTORY_ENABLED: 'true'
      ENABLED_LINKED_FILE_TYPES: 'url,project_file,project_output_file,mendeley,zotero'
      LINKED_URL_PROXY: 'http://localhost:6543'
      LOCK_MANAGER_MAX_LOCK_WAIT_TIME: 30000
      NODE_ENV: test
      SHARELATEX_CONFIG:
    command: npm run test:acceptance:app
    user: root
    depends_on:
      - redis
      - mongo

  test_frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.ci
      args:
        PROJECT_NAME: $PROJECT_NAME
        BRANCH_NAME: $BRANCH_NAME
        BUILD_NUMBER: $BUILD_NUMBER
    working_dir: /app
    command: npm run test:frontend -- --single-run
    user: node

  tar:
    image: ci/$PROJECT_NAME:$BRANCH_NAME-$BUILD_NUMBER-webpack
    volumes:
      - ./:/tmp/build/
    command: tar -cf /tmp/build/build.tar public/
    user: root

  redis:
    image: redis

  mongo:
    image: mongo:3.6.16
