version: "2"

volumes:
  data:

services:
  test_acceptance:
    image: node:6.9.5
    volumes:
      - .:/app:ro
      - data:/app/data:rw
    working_dir: /app
    environment:
      REDIS_HOST: redis
      MONGO_URL: "mongodb://mongo/sharelatex"
      SHARELATEX_ALLOW_PUBLIC_ACCESS: 'true'
      PROJECT_HISTORY_ENABLED: 'true'
      ENABLED_LINKED_FILE_TYPES: 'url'
      LINKED_URL_PROXY: 'http://localhost:6543'
      ENABLED_LINKED_FILE_TYPES: 'url,project_file,project_output_file'
      SHARELATEX_CONFIG: /app/test/acceptance/config/settings.test.coffee
    depends_on:
      - redis
      - mongo
    command: node app.js

  test_frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - .:/app
    working_dir: /app
    command: npm run test:frontend -- --single-run

  redis:
    image: redis

  mongo:
    image: mongo:3.4.6
