version: "2"

volumes:
  data:

services:

  test_unit:
    build: .
    image: ci/$PROJECT_NAME:$BRANCH_NAME-$BUILD_NUMBER
    user: node
    command: npm run test:unit

  test_acceptance:
    build: .
    image: ci/$PROJECT_NAME:$BRANCH_NAME-$BUILD_NUMBER
    working_dir: /app
    environment:
      REDIS_HOST: redis
      MONGO_URL: "mongodb://mongo/sharelatex"
      SHARELATEX_ALLOW_PUBLIC_ACCESS: 'true'
      PROJECT_HISTORY_ENABLED: 'true'
      ENABLED_LINKED_FILE_TYPES: 'url,project_file,project_output_file,mendeley,zotero'
      LINKED_URL_PROXY: 'http://localhost:6543'
      SHARELATEX_CONFIG: /app/test/acceptance/config/settings.test.coffee
      NODE_ENV: production
    user: root
    depends_on:
      - redis
      - mongo
    command: npm run test:acceptance:app

  test_frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - .:/app
    working_dir: /app
    command: npm run test:frontend -- --single-run

  tar:
    build: .
    image: ci/$PROJECT_NAME:$BRANCH_NAME-$BUILD_NUMBER
    volumes:
      - ./:/tmp/build/
    command: tar -czf /tmp/build/build.tar.gz --exclude=build.tar.gz --exclude-vcs .
    user: root

  redis:
    image: redis

  mongo:
    image: mongo:3.4.6
    container_name: mongo-ci-$BUILD_NUMBER
